version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis
    environment:
      POSTGRES_USER: gisuser
      POSTGRES_PASSWORD: gispass
      POSTGRES_DB: gisdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  #backend:
  #  build: ./backend
  #  container_name: fastapi-backend
  #  volumes:
  #    - ./backend:/app
  #  ports:
  #    - "8000:8000"
  #  depends_on:
  #    - db

  backend-node:
    build: ./backend-node
    container_name: backend-node
    ports:
      - "8001:8000"
    depends_on:
      - db

#  frontend:
#    build: ./frontend
#    container_name: react-frontend
#    ports:
#      - "80:80"
#    depends_on:
#      - node-backend
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-node
      
volumes:
  pgdata:
